name: Maven Build Artifact

on:
  pull_request:
    branches:
      - '*'

jobs:
  composite_job:
    runs-on: ubuntu-latest
    steps:
      - name: run service build
        uses: valitydev/java-workflow/.github/workflows/maven-service-build.yml@sec-24

      - name: run semgrep scan
        uses: valitydev/java-workflow/.github/workflows/semgrep-scan.yml@sec-24