name: Run Semgrep
on:
    push:
        branches:
            - '*'
                
jobs:
    semgrep:
        runs-on: ubuntu-20.04
        container:
            image: returntocorp/semgrep
                
        steps:
            - name: Checkout code
            - uses: actions/checkout@v4
            - run: semgrep ci --sarif > semgrep.sarif

              # step on
            - name: Upload SARIF results
              uses: github/codeql-action/upload-sarif@v2
              with:
                sarif_file: report.sarif
