name: Run Semgrep
on:
  push:
    branches:
      - '*'

jobs:
  semgrep:
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Semgrep
        run: semgrep --config=p/java
      
      - name: Convert Semgrep results to SARIF
        run: semgrep --sarif --config .semgrep.yml > semgrep-results.sarif

      - name: Upload SARIF results
        uses: actions/upload-artifact@v3
        with:
          name: semgrep-results
          path: semgrep-results.sarif
