name: Run Semgrep
on:
  push:
    branches:
      - '*'

jobs:
  semgrep:
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Semgrep
      # Как запустить все правила ?
      # p/CI требует учетку
        run: semgrep --config=p/java

      - uses: actions/checkout@v4
      # то что ниже работает ?
      - run: semgrep ci --sarif --config > semgrep.sarif

      - name: publish code scanning alerts
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: semgrep.sarif
