name: Run Semgrep
on:
  push:
    branches:
      - '*'

jobs:
  semgrep:
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Semgrep
        run: semgrep --config=p/java

      - name: publish code scanning alerts
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: semgrep-report.sarif
