name: Run Semgrep
on:
    push:
        branches:
            - '*'
                
jobs:
    semgrep:
        runs-on: ubuntu-20.04
                
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
              
            - name: Semgrep scan
              uses: returntocorp/semgrep@v3
              with:
                  config-file: .semgrep.yaml
                  exclude: |
                      src/generated
            
            - name: Convert Semgrep results to SARIF
              run: semgrep --sarif --config .semgrep.yaml > semgrep-results.sarif
  
            - name: Upload SARIF results
              uses: actions/upload-artifacts@v3
              with:
                name: semgrep-results
                path: semgrep-results.sarif
