name: Run Semgrep
on:
  push:
    branches:
      - '*'

jobs:
  semgrep:
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep

    steps:
      - name: Checkout code
      - uses: actions/checkout@v2

     # - name: Run Semgrep
      - run: semgrep ci --sarif > semgrep.sarif

      - name: publish code scanning alerts
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: semgrep.sarif
