name: Run Semgrep
on:
    push:
        branches:
            - '*'
                
jobs:
    semgrep:
        runs-on: ubuntu-20.04
        container:
            image: returntocorp/semgrep
                
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
              
            - name: Run Semgrep
              run: semgrep --config semgrep.yml .
            
            - name: Convert Semgrep results to SARIF
              run: semgrep --sarif --config .semgrep.yaml > semgrep-results.sarif
  
            - name: Upload SARIF results
              uses: actions/upload-artifacts@v3
              with:
                name: semgrep-results
                path: semgrep-results.sarif
