name: Run Semgrep
on:
  push:
    branches:
      - '*'

jobs:
  semgrep:
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Semgrep
        run: semgrep --config=my_rules.yaml /path/to/code --sarif-report=output.sarif
