name: Run Semgrep
on:
    push:
        branches:
            - '*'
                
jobs:
    semgrep:
        runs-on: ubuntu-20.04
        container:
          image: returntocorp/semgrep
                
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
              
            - name: full scan
              run: |
                semgrep \
                    --sarif --output report
                  --metrics=off \
                  --config="p/default"
  
            - name: publish code scanning alerts
              uses: github/codeql-action/upload-sarif@v2
              with:
                sarif_file: report.sarif
                category: semgrep
